---
- name: generate report
  hosts: all
  vars:
    header: |
      HOSTNAME,OS,IP_ADDRESS,RAM_MB
    report: |
      {{ ansible_hostname }},{{ansible_distribution}} {{ansible_distribution_release}} {{ansible_distribution_version}},{{ ansible_default_ipv4.address }},{{ ansible_memtotal_mb }}
  tasks:
    - name: create report using copy
      copy:
        content: "{{ report }}"
        dest: "/tmp/{{ ansible_hostname }}.csv"
    - name: fetch to control node
      fetch:
        src: "/tmp/{{ ansible_hostname }}.csv"
        dest: /tmp/reports/
        flat: true
    - name: use shell on control node
      shell: cat /tmp/reports/* > /tmp/master_report.csv
      delegate_to: localhost
      run_once: true
    - name: create new file with header
      copy:
        content: "{{ header }}"
        dest: /tmp/reports/report.csv
      delegate_to: localhost
      run_once: true
    - name: merge files
      shell: cat /tmp/master_report.csv >> /tmp/reports/report.csv
      delegate_to: localhost
      run_once: true
